import type { Metadata } from "next";
import "./globals.css";
import { getCurrentUserName } from '../actions/auth'
import { Header } from '../components/header'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const userName = await getCurrentUserName()
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <Header userName={userName}></Header>
        {children}
      </body>
    </html>
  );
}
