import type { Metadata } from "next";
import "./globals.css";
import { Header } from '../components/Header/header'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="initial-scale=1, width=device-width" />
      </head>
      <body className='antialiased'>
        <Header></Header>
        {children}
      </body>
    </html>
  );
}
